### ISSUE TITLE
[Question]: Splitting on fixed time vs splitting on silence

### ISSUE THREAD

**Issue by sebnun** [gkorepanov/whisper-stream#1]
Hi, thanks for this library.

I see whisper uses chunks of 30 seconds internally, but also on the docs they mention " we suggest that you avoid breaking the audio up mid-sentence as this may cause some context to be lost"
https://platform.openai.com/docs/guides/speech-to-text/longer-inputs

Do you know if the accuracy can be improved splitting chunks using something like pydub's split_on_silence()?

**Comment by sebnun** [comment]
After doing some testing with https://github.com/mpirescarvalho/audio-splitter I see that "silence" maybe is not the optimal way to split it either if the audio has background noise or music. Maybe a better way is to use some voice activity detection library, but of course the complexity also increases.

**Comment by gkorepanov** [comment]
Hi, actually the way chunking works for Whisper is a little bit different. Instead of splitting at predefined time positions, we split at segments ends. Segments are returned by Whisper itself. Step by step, it can be described as

1. We send [0s - 30s] chunk to API 
2. We receive a list of segments, let it be, say, 5 full segments, and one more incomplete last segment, for example it can be [24s - 30s]
3. We discard the last segment and send the next audio chunk starting from the end of previous segment, e.g. [24s - 54s]

This way the resulting text is almost invariant to initial chunk split positions, because Whisper itself acts as voice activity detector by splitting the voice into segments. There are some corner cases though (for example when the chunk contains only one segment) but in my experience they are pretty rare
